apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::146454414795:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IY1F2AJPJNUZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::146454414795:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-03T20:41:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1532"
  uid: 86d1774c-cd3d-4705-86ca-4a339425b823
